#!/bin/bash
set -x
cd opensaf-*
branch=default

[[ ! -z $1 ]] && branch=$1
flags="--enable-imm-pbe --disable-ais-plm --disable-ais-msg --disable-ais-lck --disable-ais-evt --disable-ais-ckpt --enable-tipc"
shift
[[ ! -z $1 ]] && flags="$@"
hg update $branch
./bootstrap.sh
./configure $flags
