#!/bin/bash
cd opensaf-*
branch=default
[[ ! -z $1 ]] && branch=$1
hg update $branch
./bootstrap.sh
./configure --enable-imm-pbe --disable-ais-plm --disable-ais-msg --disable-ais-lck --disable-ais-evt --disable-ais-ckpt --enable-tipc
