#!/bin/bash
# Support script for docker
#
VERSION=build_1.0
DVERSION=ubuntu_15
[[ ! -z $1 ]] && VERSION=$1
echo Building with version $VERSION

. ../../bin/for-docker/common-routines

docker build -f Dockerfile.ubuntu_15_buildsystem -t="adrianszwej/opensaf:$VERSION-$DVERSION" . 
