#!/bin/bash
# Support script for docker
#
VERSION=build_1.0
DVERSION=ubuntu_14
[[ ! -z $1 ]] && VERSION=$1
echo Building with version $VERSION

. ../../bin/for-docker/common-routines

docker build -f Dockerfile.ubuntu_14_buildsystem -t="adrianszwej/opensaf:$VERSION-$DVERSION" . 
