#!/bin/bash
# Support script for docker
#
VERSION=4.6
[[ ! -z $1 ]] && VERSION=$1
echo Building with version $VERSION

. ../../bin/for-docker/common-routines

docker build -t="adrianszwej/opensaf:$VERSION-fedora-21" . 
