FROM adrianszwej/private:rhel6.5-cba-base 
MAINTAINER Adrian Szwej <adrian.szwej@ericsson.com>
# @Version: 1.0
# Ngee POC controller node 

RUN install ngee-controller-sw-v
# Add special configuration for demo

#TODO 3 change /etc/tipc-nodes to SC-1

# Pass configuration for utility scripts
ENV container docker

CMD ["/bin/bash"]
