#!/bin/bash
# Support script for docker
#
VERSION=build_1.0
DVERSION=fedora_21
[[ ! -z $1 ]] && VERSION=$1 && branch=opensaf-$VERSION-x && shift
echo Building with version $VERSION

. ../../bin/for-docker/common-routines

docker build $DBUILD -f Dockerfile.${DVERSION}_buildsystem -t="adrianszwej/opensaf:$VERSION-$DVERSION" . 
