#!/bin/bash
# Support script for docker
#
VERSION=4.7
DVERSION=fedora_22

[[ ! -z $1 ]] && VERSION=$1
echo Create baseimage with product version $VERSION

. ../../bin/for-docker/common-routines

docker build -f Dockerfile.image-$DVERSION -t="adrianszwej/opensaf:$VERSION-$DVERSION" . 
