#!/bin/bash
# Node configuration script for opensaf node
#
# @version: 1.3
#   added environment variable IFACE & NODEID & TYPE for hinting about the interface to use for internal communication. Prefix is enough.
# @version: 1.2
#   added container configuration file support
#   added tipc network prefix
#   added tipc_manage configuration options to indicate if container should set the tipc address
# @version: 1.1
#   added tipc configuration support
# @version: 1.0
#   initial version
#
# @Author: Adrian Szwej <adrian.szwej@gmail.com>

iface=eth0
[[ $IFACE ]] && iface=`ifconfig | grep ^$IFACE | cut -d " " -f1`
[[ $NODEID ]] && nodeid=$NODEID
[[ $TYPE ]] && type=$TYPE
controllers=2
payloads=8

#tipc configuration
tipc_netid=1234
tipc_prefix=1.1
tipc_be=eth:$iface
tipc_manage=yes
tipc_multicast=no
#tcp configuration
mcast=224.0.0.6

[[ -z $TIPC ]] && TIPC=no
[[ -f /etc/container.env ]] && source /etc/container.env

# For some reason -disable-ais-plm does not work on fedora
sed -e 's/^\/usr\/local\/lib\/opensaf\/clc-cli\/osaf-plmd\:PLMD/#\/usr\/local\/lib\/opensaf\/clc-cli\/osaf-plmd\:PLMD/' -i /etc/opensaf/nodeinit.conf.controller

# Enable sqlite3 db configuration
sed -e 's/#export IMMSV_PBE_FILE=imm.db/export IMMSV_PBE_FILE=imm.db/' -i /etc/opensaf/immnd.conf

# default imm configuration location
immdir=/etc/opensaf

# If the user have exposed sharefs dir; use that instead
if [ -d /etc/opensaf/sharedfs ]; then
  immdir=/etc/opensaf/sharedfs
  sed s/^export.IMMSV_ROOT_DIRECTORY=.*/"export IMMSV_ROOT_DIRECTORY=\/etc\/opensaf\/sharedfs"/ -i /etc/opensaf/immnd.conf
  sed s/^export.IMMSV_MAX_WAIT=.*/"export IMMSV_MAX_WAIT=0"/ -i /etc/opensaf/immnd.conf
fi

# Host specific configuration
[[ -z $nodeid ]] && nodeid=`hostname | cut -d "-" -f 2`
echo $nodeid > /etc/opensaf/slot_id
[[ -z $type ]] && type=`hostname | cut -d "-" -f 1`
if [ $type = "PL" ]; then
  echo "payload" > /etc/opensaf/node_type
else
  echo "controller" > /etc/opensaf/node_type
fi
echo ${type}-$nodeid > /etc/opensaf/node_name

[[ "$TIPC" = "yes" ]] && ((lsmod | grep "^tipc " > /dev/null) || (echo "Error! The host OS does not have tipc module loaded. Try 'modprobe tipc' in the host os." && exit 1))

if [ "$TIPC" = "yes" ]; then
  sed 's/export MDS_TRANSPORT=TCP/export MDS_TRANSPORT=TIPC/' -i /etc/opensaf/nid.conf
  [[ "$tipc_multicast" = "no" ]] && sed 's/export MDS_TIPC_MCAST_ENABLED=1/export MDS_TIPC_MCAST_ENABLED=0/' -i /etc/opensaf/nid.conf
  sed s/TIPC_ETH_IF=eth0/TIPC_ETH_IF=$iface/ -i /etc/opensaf/nid.conf
  sed s/TIPC_NET_ID=1234/TIPC_NET_ID=$tipc_netid/ -i /etc/opensaf/nid.conf
  if [ "${tipc_manage}" = "yes" ]; then
    tipc-config -netid=$tipc_netid
    tipc-config -a=${tipc_prefix}.`cat /etc/opensaf/slot_id`
    tipc-config -be=$tipc_be
  fi
else
  ip=`ifconfig $iface | grep inet | grep -v inet6 | grep -Po '(?<=(inet )|(inet addr:))[0-9].*' | cut -d " " -f1`
  sed s/DTM_NODE_IP=.*/DTM_NODE_IP=$ip/ -i /etc/opensaf/dtmd.conf

  # Configure the multicast address
  #sed s/DTM_MCAST_ADDR=.*/DTM_MCAST_ADDR=$mcast/ -i /etc/opensaf/dtmd.conf
fi

# Configuration of the firewall only applicable when using with fedora and systemd
iptables --version > /dev/null 2>&1
if [ $? -eq 0 ]; then
  iptables -I INPUT 1 -d $mcast -p udp --dport 6900 -m pkttype --pkt-type multicast -j ACCEPT
  iptables -I INPUT 1 -p tcp --dport 6700 -m conntrack --ctstate NEW -j ACCEPT
fi

if [ $(cat /etc/opensaf/node_type) = "controller" ]; then
  if [ ! -f $immdir/imm.xml ]; then
    cd /usr/local/share/opensaf/immxml
    rm -f imm.xml.*
    ./immxml-clustersize -s $controllers -p $payloads
    ./immxml-configure
    cp imm.xml.* $immdir/imm.xml
    # Enable Persistent Backend
    sed '/safRdn=immManagement,safApp=safImmService/,/<\/attr>/ { s/2/1/g; }' -i $immdir/imm.xml
    rm -f imm.xml.*
  fi
fi

# Sometimes these were not properly cleaned 
rm -rf /var/run/opensaf/*

# Make sure permissions are set for non root
chown opensaf:opensaf /var/lib/opensaf
chown opensaf:opensaf /var/run/opensaf
chown -R opensaf:opensaf /var/log/opensaf
chown -R opensaf:opensaf /etc/opensaf
