#!/bin/bash
# Support script for building opensaf releases
#
VERSION=4.7
OS=opensuse
[[ -z $DVERSION ]] && DVERSION=13.1
[[ ! -z $1 ]] && VERSION=$1 && branch=opensaf-${VERSION}.x && shift
echo "Building product version $VERSION for OS ${OS}_$DVERSION"

docker run -ti --name release_$VERSION-${OS}_$DVERSION adrianszwej/opensaf:build_1.0-${OS}_$DVERSION $branch $@
