#!/bin/bash
[[ -z $1 ]] && echo Specify number of controllers && exit 1
[[ -z $2 ]] && echo Specify number of payloads && exit 1

# Default image to instansiate containers from
#image=adrianszwej/opensaf:4.6-debian-8.0
IMAGE=adrianszwej/opensaf:4.7.patched-ubuntu-15
CMD="/etc/init.d/opensafd start"
NETPREFIX=1.1

[[ ! -z $3 ]] && IMAGE=$3 
CLUSTERNAME=default

[[ ! -z $4 ]] && CLUSTERNAME=$4 

SCs=$1
PLs=$2
# If TIPC address should be set outside the container
TIPC_MANAGE=yes

# If TIPC should be using the macvlan intra interface
TIPC_INTRA=yes
# Which parent interface to use when macvlan are created ontop
NETIF=eth0

[[ -z $OFFSET ]] && OFFSET=0
[[ -z $SC_OFFSET ]] && SC_OFFSET=0
[[ -z $STORAGE ]] && STORAGE=~/sharedfs
SFS=$STORAGE/$CLUSTERNAME
mkdir -p $SFS > /dev/null

# To be removed for final version
cp ../for-running/etc/container.env $SFS

mkdir -p /var/run/netns > /dev/null
__check_tipc_module()
{
   lsmod | grep tipc > /dev/null || (echo "TIPC module is not loaded" && exit 1)
}

[[ -z $TIPC ]] && TIPC=yes && __check_tipc_module || exit 1
C_OPTS="--env TIPC=$TIPC"

__create_tipc_namespace()
{
   local pid=$1
   local nodeid=${NETPREFIX}.$2
   ln -s /proc/$pid/ns/net /var/run/netns/$pid
   ../../../bin/for-docker/tipc-namespace-setup $pid $nodeid $TIPC_MANAGE $NETIF
}

__create_container()
{
    echo "Creating container $name"

    docker run --privileged -t -d -i --name $1 -h $2 $C_OPTS -v $SFS:/etc/opensaf/sharedfs -v $SFS/container.env:/etc/container.env $IMAGE /bin/bash
   
    if [ "$TIPC" = "yes" -a "${TIPC_INTRA}" = "yes" ]; then
       PID=`docker inspect -f '{{.State.Pid}}' $1`
       __create_tipc_namespace $PID ${2/*-}
    fi
}

__create_scs()
{
	i=$SC_OFFSET
	while [ $i -lt $(($SCs + SC_OFFSET)) ]; do
	   i=$(($i + 1))
	   node=SC-$i 
	   name=$CLUSTERNAME-SC-$i
	   docker inspect $name > /dev/null 2>&1
	   if [ $? -ne 0 ]; then 
	     __create_container $name $node
             docker exec $name $CMD
	   fi
	done
}

__create_pls()
{
	i=$((2 + OFFSET))
	while [ $i -lt $((PLs + OFFSET + 2)) ]; do
	   i=$(($i + 1))
	   node=PL-$i             
	   name=$CLUSTERNAME-PL-$i
	   docker inspect $name > /dev/null 2>&1
	   if [ $? -ne 0 ]; then
	     __create_container $name $node
             docker exec $name $CMD
	   fi
	done
}

__create_scs 
__create_pls

exit 0
