#!/bin/bash
# Cluster management cluster
# - provides status of the cluster instances 

clustername=default
[[ ! -z $1 ]] && clustername=$1 
SFS=~/sharedfs/$clustername

__get_containers()
{
   docker ps -a | grep -o "${clustername}-[PS][LC]-[0-9]*" 
}

__status_containers()
{
   for name in $@; do
      pid=`docker inspect -f '{{.State.Pid}}' $name`
      address=`ip netns exec $pid tipc-config -a | grep -o "<.*>"`

      up=`ip netns exec $pid tipc-config -l | grep ": up" | wc -l`
      down=`ip netns exec $pid tipc-config -l | grep ": down" | wc -l`
      echo "$name $address LinksUp: $up. LinksDown: $down"
   done
}

__status_containers $(__get_containers)
