#!/bin/bash
# Cluster management cluster
# - destroy all cluster instances 

clustername=default
[[ ! -z $1 ]] && clustername=$1 
SFS=~/sharedfs/$clustername

__get_containers()
{
   docker ps -a | grep -o "${clustername}-[PS][LC]-[0-9]*" 
}

__destroy_containers()
{
   for name in $@; do
      echo -n "Destroying container $name..."
      pid=`docker inspect -f '{{.State.Pid}}' $name`
      [[ $pid -ne 0 ]] && ../../../bin/for-docker/tipc-namespace-teardown $pid
      docker stop $name > /dev/null
 
      # Finally delete the container
      docker rm $name > /dev/null
      if [ $? -eq 0 ]; then
         echo "done"
      else
         echo "failed"
      fi
   done
}

__destroy_containers $(__get_containers)

# delete the sharedfs
rm -rf $SFS > /dev/null
