#!/bin/bash
# Support script for building opensaf releases
#
VERSION=4.7
OS=centos
[[ -z $DVERSION ]] && DVERSION=7
[[ ! -z $1 ]] && VERSION=$1 && branch=opensaf-${VERSION}.x && shift
echo "Building product version $VERSION for OS ${OS}_$DVERSION"
OUT=/tmp/$USER/OSAF_release
[[ -d $OUT ]] && rm -rf $OUT && echo "Cleaning previous OUT directory"
mkdir -p $OUT > /dev/null
#. ../../bin/for-docker/common-routines

#docker build -f Dockerfile.builder-${OS}_$DVERSION -t="adrianszwej/opensaf:release_$VERSION-${OS}_$DVERSION" . 

docker run -ti -v $OUT:/OUT:rw --name release_$VERSION-${OS}_$DVERSION adrianszwej/opensaf:build_1.0-${OS}_$DVERSION
