FROM richxsl/rhel6.5:latest 
MAINTAINER Adrian Szwej <adrian.szwej@ericsson.com>
# @Version: 1.0
# Base image providing RHEL 6.5 base image with basic common packages installed 

# Pass configuration for utility scripts
ENV container docker

CMD ["/bin/bash"]
