FROM ubuntu:14.04.2
MAINTAINER Adrian Szwej <adrian.szwej@gmail.com>
COPY swarm.discovery /
RUN apt-get -y install wget avahi-utils
RUN wget https://get.docker.com/builds/Linux/x86_64/docker-1.6.0
RUN mv docker-1.6.0 /usr/bin/docker
RUN chmod u+x /usr/bin/docker
RUN mkdir -p /etc/swarm
ADD nodes.conf /etc/swarm/
VOLUME /etc/swarm
CMD ["/swarm.discovery"]

#ENV GROUP=COM_SUT1
